# Generated by Django 4.2.2 on 2023-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Education_Details',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Mother_Tongue',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Place_of_Birth',
            new_name='My_Complexion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Sub_Cast',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Occupation_Details',
        ),
        migrations.AddField(
            model_name='profile',
            name='Education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
