# Generated by Django 4.2.2 on 2023-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0006_alter_interest_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
