# Generated by Django 4.2.4 on 2023-09-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0012_profile_facebook_link_profile_instagram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_link',
        ),
    ]
